baseURL = "http://example.org"
languageCode = "zh-hans"
defaultContentLanguage = "zh-hans"
title = "blog title"
theme = "example_blog_theme"

# 这里的 pygments 设置用于代码的高亮处理
pygmentsCodefences  = true
pygmentsUseClasses  = true

hasCJKLanguage = true
# 如果 Chinese/Japanese/Korean 是这个博客的主要语言, 启用这个选项好让负责字数统计的程序可以正确的计数.

rssLimit = 10
# RSS feed 中条目的最大显示数量.

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# 这条信息只会被 RSS template 使用.

enableEmoji = true
# 在你的博客里启用 emoji 表情，表情的代码可以在这里查阅 - https://www.webfx.com/tools/emoji-cheat-sheet/
# 比如 "你好 :heart: 世界"，其中 ":heart:" 会被翻译成 emoji 中的 爱心

[author]
  name = "作者的名字"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  themeColor = "#494f5c"

  homeSubtitle = "A minimal and fast blog built by hugo"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/"

  [[params.social]]
    name = "github"
    url = "https://github.com/"

[menu]

  [[menu.main]]
    name = "About"
    url = "about_me/"
    weight = 10
